import datetime
from enum import Enum
from typing import Dict, List, Optional, Tuple
from backtester.strategy import SignalEvent, SignalType # For type hinting
from backtester.data import MarketDataEvent # For market prices

class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT" # Not fully implemented in PoC execution

class OrderStatus(Enum):
    PENDING = "PENDING"
    FILLED = "FILLED"
    CANCELED = "CANCELED" # Not fully implemented in PoC

class OrderEvent:
    """
    Represents an order to be sent to an (simulated) exchange.
    Generated by the Portfolio based on Signals.
    """
    def __init__(self, timestamp: datetime.datetime, symbol: str, order_type: OrderType, quantity: int, direction: SignalType): # Direction BUY/SELL
        self.type = 'ORDER'
        self.timestamp = timestamp
        self.symbol = symbol
        self.order_type = order_type
        self.quantity = quantity
        self.direction = direction # SignalType.BUY or SignalType.SELL
        self.status = OrderStatus.PENDING

    def __str__(self):
        return f"Order: {self.timestamp} {self.direction.value} {self.quantity} {self.symbol} [{self.order_type.value}] Status: {self.status.value}"

class FillEvent:
    """
    Represents a filled order.
    Generated by the (simulated) execution handler.
    """
    def __init__(self, timestamp: datetime.datetime, symbol: str, quantity: int, direction: SignalType, fill_price: float, commission: float = 0.0):
        self.type = 'FILL'
        self.timestamp = timestamp
        self.symbol = symbol
        self.quantity = quantity # Number of shares filled
        self.direction = direction # BUY or SELL
        self.fill_price = fill_price
        self.commission = commission
        self.cost = (fill_price * quantity) + commission if direction == SignalType.BUY else (fill_price * quantity) - commission

    def __str__(self):
        return f"Fill: {self.timestamp} {self.direction.value} {self.quantity} {self.symbol} @ {self.fill_price:.2f} Cost: {self.cost:.2f} Comm: {self.commission:.2f}"


class Portfolio:
    """
    Manages positions, cash, and simulates order execution.
    Updates portfolio value based on market data.
    """
    def __init__(self, initial_cash: float = 100000.0, data_handler=None): # data_handler for current prices
        self.initial_cash = initial_cash
        self.current_cash = initial_cash
        self.current_holdings: Dict[str, Dict] = {} # {'AAPL': {'quantity': 10, 'average_price': 150.0}, ...}
        self.all_positions_over_time: List[Dict] = [] # Snapshot of holdings at each bar
        self.all_cash_over_time: List[float] = [] # Snapshot of cash at each bar
        self.portfolio_value_over_time: List[float] = [] # Snapshot of total value
        self.trades: List[FillEvent] = []
        self.data_handler = data_handler # To get current prices for MTM and execution simulation

    def update_timeindex(self, current_timestamp: datetime.datetime, current_market_data: Dict[str, MarketDataEvent]):
        """
        Updates the portfolio value (mark-to-market) based on the latest market data.
        This should be called at each heartbeat of the backtest (e.g., each new bar).
        `current_market_data` is a dict: {symbol: MarketDataEvent}
        """
        portfolio_value = self.current_cash
        for symbol, position in self.current_holdings.items():
            market_event = current_market_data.get(symbol)
            if market_event and market_event.get('CLOSE') is not None:
                market_price = market_event.get('CLOSE')
                portfolio_value += position['quantity'] * market_price
            elif position['quantity'] != 0: # If no market data, use last known average price (less accurate)
                portfolio_value += position['quantity'] * position['average_price']

        self.portfolio_value_over_time.append({'timestamp': current_timestamp, 'value': portfolio_value})
        self.all_positions_over_time.append({'timestamp': current_timestamp, 'holdings': dict(self.current_holdings)}) # Store a copy
        self.all_cash_over_time.append({'timestamp': current_timestamp, 'cash': self.current_cash})
        # print(f"Portfolio updated at {current_timestamp}. Cash: {self.current_cash:.2f}, Holdings Value: {portfolio_value - self.current_cash:.2f}, Total Value: {portfolio_value:.2f}")


    def process_signal(self, signal: SignalEvent) -> Optional[OrderEvent]:
        """
        Converts a SignalEvent into an OrderEvent if the signal is valid.
        For PoC, assumes all signals are for Market orders.
        """
        if signal.type != 'SIGNAL':
            return None

        # Basic risk check: enough cash for BUY, or holding for SELL
        if signal.signal_type == SignalType.BUY:
            # Estimate cost - for PoC, we don't know fill price yet.
            # A more complex portfolio would use current market price for estimation.
            # For now, we'll let it create an order and check during execution simulation.
            pass
        elif signal.signal_type == SignalType.SELL:
            if signal.symbol not in self.current_holdings or \
               self.current_holdings[signal.symbol]['quantity'] < signal.quantity:
                print(f"Portfolio: Cannot process SELL signal for {signal.symbol}. Not enough holdings.")
                return None # Or create a REJECTED order status

        order = OrderEvent(
            timestamp=signal.timestamp,
            symbol=signal.symbol,
            order_type=OrderType.MARKET, # PoC: only market orders
            quantity=signal.quantity,
            direction=signal.signal_type
        )
        print(f"Portfolio: Generated Order: {order}")
        return order

    def process_fill(self, fill: FillEvent):
        """
        Updates holdings and cash based on a FillEvent.
        """
        if fill.type != 'FILL':
            return

        self.trades.append(fill)
        symbol = fill.symbol

        if symbol not in self.current_holdings:
            self.current_holdings[symbol] = {'quantity': 0, 'average_price': 0.0, 'cost_basis': 0.0}

        current_qty = self.current_holdings[symbol]['quantity']
        current_avg_price = self.current_holdings[symbol]['average_price']
        current_cost_basis = self.current_holdings[symbol]['cost_basis']

        if fill.direction == SignalType.BUY:
            self.current_cash -= fill.cost # Cost is positive for buys

            new_total_cost = current_cost_basis + fill.cost
            new_total_quantity = current_qty + fill.quantity

            self.current_holdings[symbol]['quantity'] = new_total_quantity
            if new_total_quantity > 0: # Avoid division by zero
                 self.current_holdings[symbol]['average_price'] = new_total_cost / new_total_quantity
            else: # Should not happen if buying, but good for consistency
                 self.current_holdings[symbol]['average_price'] = 0.0
            self.current_holdings[symbol]['cost_basis'] = new_total_cost

        elif fill.direction == SignalType.SELL:
            # For sells, fill.cost is negative (value received), so subtracting it increases cash
            self.current_cash -= fill.cost # fill.cost is (price * qty) - commission, so cash increases by this amount

            # Reduce quantity. Average price of remaining shares doesn't change.
            # Realized P&L would be calculated here in a more complex system.
            self.current_holdings[symbol]['quantity'] = current_qty - fill.quantity
            # Update cost basis: reduce by the cost of shares sold (qty_sold * avg_price_of_lot)
            # For simplicity, using average price for cost basis reduction. FIFO/LIFO would be more complex.
            sold_cost = fill.quantity * current_avg_price
            self.current_holdings[symbol]['cost_basis'] = current_cost_basis - sold_cost

            if self.current_holdings[symbol]['quantity'] == 0:
                self.current_holdings[symbol]['average_price'] = 0.0 # Reset if all sold
                self.current_holdings[symbol]['cost_basis'] = 0.0


        print(f"Portfolio: Processed Fill: {fill}. Cash: {self.current_cash:.2f}")
        print(f"Portfolio: Holdings for {symbol}: {self.current_holdings[symbol]['quantity']} shares @ avg price {self.current_holdings[symbol]['average_price']:.2f}")


    # --- Simulation specific method for Execution ---
    def simulate_order_execution(self, order: OrderEvent, market_event: MarketDataEvent) -> Optional[FillEvent]:
        """
        Simulates the execution of an order.
        For PoC: Market orders are filled at the OPEN price of the *next* bar (represented by current market_event).
        Slippage and commission can be added here.
        """
        if order.type != 'ORDER' or order.status != OrderStatus.PENDING:
            return None

        if order.symbol != market_event.symbol:
            # This should not happen if events are routed correctly
            print(f"Warning: Order symbol {order.symbol} and market event symbol {market_event.symbol} mismatch during execution.")
            return None

        # PoC: Fill at open price of the current bar (acting as next bar's open for previous bar's signal)
        fill_price = market_event.get('OPEN')
        if fill_price is None:
            print(f"Portfolio: Could not execute order {order.order_id} for {order.symbol}, no OPEN price in market data.")
            return None # Or reject order

        # Basic check for BUY orders: sufficient cash
        # This is a simplified check. A real system might have margin.
        if order.direction == SignalType.BUY:
            estimated_cost = fill_price * order.quantity # Ignoring commission for this check
            if self.current_cash < estimated_cost:
                print(f"Portfolio: Insufficient cash to execute BUY order for {order.quantity} {order.symbol} at {fill_price}. Have {self.current_cash}, need ~{estimated_cost}")
                # Here you might reject the order or partially fill if allowed. PoC: reject.
                return None

        # PoC: Simple fixed commission
        commission = 1.00 # Example: $1 per trade

        fill = FillEvent(
            timestamp=market_event.timestamp, # Fill occurs at the time of this market event
            symbol=order.symbol,
            quantity=order.quantity,
            direction=order.direction,
            fill_price=fill_price,
            commission=commission
        )
        order.status = OrderStatus.FILLED # Update order status
        print(f"Portfolio: Simulated execution for order: {order.direction.value} {order.quantity} {order.symbol} -> Fill at {fill_price}")
        return fill

if __name__ == '__main__':
    # Example Usage
    # Needs SignalEvent, MarketDataEvent
    try:
        import pandas as pd # For dummy timestamps
        from backtester.data import MarketDataEvent # For dummy data
        from backtester.strategy import SignalEvent, SignalType # For dummy signals
    except ImportError:
        print("Ensure pandas is installed and script is run in an environment where backtester module is found.")
        exit()

    portfolio = Portfolio(initial_cash=50000.0)

    # 1. Simulate portfolio update at a new bar
    dummy_ts = pd.Timestamp('2023-01-01 09:30:00')
    market_data_snap = {
        'AAPL': MarketDataEvent(dummy_ts, 'AAPL', {'OPEN':150, 'HIGH':151, 'LOW':149, 'CLOSE':150.5, 'VOLUME':1000}),
        'GOOG': MarketDataEvent(dummy_ts, 'GOOG', {'OPEN':2500, 'HIGH':2510, 'LOW':2490, 'CLOSE':2505, 'VOLUME':500})
    }
    portfolio.update_timeindex(dummy_ts, market_data_snap)
    print(f"Initial Portfolio Value: {portfolio.portfolio_value_over_time[-1]['value']:.2f}")

    # 2. Simulate a BUY signal and its processing
    buy_signal_aapl = SignalEvent(dummy_ts, 'AAPL', SignalType.BUY, quantity=10)
    buy_order_aapl = portfolio.process_signal(buy_signal_aapl)

    # 3. Simulate execution of that order with the next market bar
    next_dummy_ts = pd.Timestamp('2023-01-01 09:31:00')
    market_event_aapl_next_bar = MarketDataEvent(next_dummy_ts, 'AAPL', {'OPEN':151, 'HIGH':152, 'LOW':150.5, 'CLOSE':151.5, 'VOLUME':1200})

    if buy_order_aapl:
        fill_event_aapl = portfolio.simulate_order_execution(buy_order_aapl, market_event_aapl_next_bar)
        if fill_event_aapl:
            portfolio.process_fill(fill_event_aapl)
            print(f"AAPL Holdings: {portfolio.current_holdings.get('AAPL')}")

    # 4. Update portfolio value again
    market_data_snap_2 = {
        'AAPL': market_event_aapl_next_bar, # AAPL's price changed
        'GOOG': MarketDataEvent(next_dummy_ts, 'GOOG', {'OPEN':2505, 'HIGH':2515, 'LOW':2495, 'CLOSE':2500, 'VOLUME':550}) # GOOG also moved
    }
    portfolio.update_timeindex(next_dummy_ts, market_data_snap_2)
    print(f"Portfolio Value after trade and market move: {portfolio.portfolio_value_over_time[-1]['value']:.2f}")

    # 5. Simulate a SELL signal and processing for partial sale
    sell_signal_aapl = SignalEvent(next_dummy_ts, 'AAPL', SignalType.SELL, quantity=5)
    sell_order_aapl = portfolio.process_signal(sell_signal_aapl)

    # 6. Simulate execution of the SELL order
    next_dummy_ts_2 = pd.Timestamp('2023-01-01 09:32:00')
    market_event_aapl_next_bar_2 = MarketDataEvent(next_dummy_ts_2, 'AAPL', {'OPEN':152, 'HIGH':153, 'LOW':151.5, 'CLOSE':152.5, 'VOLUME':1300})
    if sell_order_aapl:
        fill_event_sell_aapl = portfolio.simulate_order_execution(sell_order_aapl, market_event_aapl_next_bar_2)
        if fill_event_sell_aapl:
            portfolio.process_fill(fill_event_sell_aapl)
            print(f"AAPL Holdings after sell: {portfolio.current_holdings.get('AAPL')}")
            print(f"Total Trades: {len(portfolio.trades)}")
            for trade in portfolio.trades: print(trade)

    portfolio.update_timeindex(next_dummy_ts_2, {'AAPL': market_event_aapl_next_bar_2, 'GOOG': market_data_snap_2['GOOG']}) # GOOG data is stale here for simplicity
    print(f"Final Portfolio Value: {portfolio.portfolio_value_over_time[-1]['value']:.2f}")
    print(f"Final Cash: {portfolio.current_cash:.2f}")
    print(f"Final Holdings: {portfolio.current_holdings}")
