from abc import ABC, abstractmethod
from backtester.data import MarketDataEvent # Assuming MarketDataEvent is in data.py
from enum import Enum
import datetime # For SignalEvent timestamp

class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD" # Or EXIT/FLATTEN

class SignalEvent:
    """
    Represents a trading signal generated by a strategy.
    """
    def __init__(self, timestamp: datetime.datetime, symbol: str, signal_type: SignalType, quantity: int, price: float = None, details: str = ""):
        self.type = 'SIGNAL'
        self.timestamp = timestamp
        self.symbol = symbol
        self.signal_type = signal_type # BUY, SELL
        self.quantity = quantity # Number of shares/contracts
        self.price = price # Optional: for limit orders, or to record execution price idea
        self.details = details # e.g., "MA Crossover"

    def __str__(self):
        return f"Signal: {self.timestamp} {self.signal_type.value} {self.quantity} {self.symbol}" + (f" @ {self.price}" if self.price else "")


class AbstractStrategy(ABC):
    """
    Abstract base class for trading strategies.
    Strategies generate SignalEvents based on MarketDataEvents.
    """
    def __init__(self, symbols: list[str]):
        self.symbols = symbols
        self.active_signals = [] # List to store generated signals

    @abstractmethod
    def calculate_signals(self, event: MarketDataEvent) -> list[SignalEvent]:
        """
        Processes a MarketDataEvent and returns a list of SignalEvents.
        This is the core logic of the strategy.
        """
        raise NotImplementedError

    def get_new_signals(self) -> list[SignalEvent]:
        """Returns new signals and clears the internal list."""
        signals = list(self.active_signals)
        self.active_signals.clear()
        return signals

class BuyAndHoldStrategy(AbstractStrategy):
    """
    A simple buy-and-hold strategy.
    Buys a fixed quantity of each symbol on the first bar of data received
    and then holds.
    """
    def __init__(self, symbols: list[str], initial_quantity: int = 100):
        super().__init__(symbols)
        self.initial_quantity = initial_quantity
        self.invested = {symbol: False for symbol in symbols}

    def calculate_signals(self, event: MarketDataEvent) -> list[SignalEvent]:
        """
        Generates a BUY signal for each symbol on the first data bar received for that symbol.
        """
        new_signals = []
        if event.type == 'MARKET_DATA' and event.symbol in self.symbols:
            if not self.invested[event.symbol]:
                # Buy on the first bar for this symbol
                signal = SignalEvent(
                    timestamp=event.timestamp,
                    symbol=event.symbol,
                    signal_type=SignalType.BUY,
                    quantity=self.initial_quantity,
                    details=f"Initial buy for Buy and Hold strategy at first bar observed: {event.timestamp}"
                )
                self.active_signals.append(signal)
                new_signals.append(signal)
                self.invested[event.symbol] = True
                print(f"{self.__class__.__name__}: Generated BUY signal for {event.symbol} at {event.timestamp}")
        return new_signals


if __name__ == '__main__':
    # Example Usage
    strategy = BuyAndHoldStrategy(symbols=['AAPL', 'GOOG'], initial_quantity=10)

    # Simulate some market data events
    dummy_market_data_aapl_bar1 = MarketDataEvent(
        timestamp=pd.Timestamp('2023-01-01 10:00:00'),
        symbol='AAPL',
        data={'OPEN': 150.0, 'CLOSE': 150.1}
    )
    dummy_market_data_goog_bar1 = MarketDataEvent(
        timestamp=pd.Timestamp('2023-01-01 10:00:00'),
        symbol='GOOG',
        data={'OPEN': 2500.0, 'CLOSE': 2501.0}
    )
    dummy_market_data_aapl_bar2 = MarketDataEvent(
        timestamp=pd.Timestamp('2023-01-01 10:01:00'),
        symbol='AAPL',
        data={'OPEN': 150.1, 'CLOSE': 150.2}
    )

    print("Processing first AAPL bar:")
    signals1 = strategy.calculate_signals(dummy_market_data_aapl_bar1)
    for s in signals1: print(s)

    print("\nProcessing first GOOG bar:")
    signals2 = strategy.calculate_signals(dummy_market_data_goog_bar1)
    for s in signals2: print(s)

    print("\nProcessing second AAPL bar (should generate no new signals):")
    signals3 = strategy.calculate_signals(dummy_market_data_aapl_bar2)
    if not signals3:
        print("No new signals, as expected.")
    for s in signals3: print(s)

    print("\nRetrieving all collected signals from strategy:")
    all_signals = strategy.get_new_signals()
    for s in all_signals: print(s)

    print("\nSignals list should now be empty in strategy:")
    print(f"Signals in strategy: {strategy.get_new_signals()}")

    # Need pandas for pd.Timestamp in example if run directly
    # Ensure to install pandas if not already installed.
    # This example requires backtester.data.MarketDataEvent.
    # For direct execution, ensure Python can find the backtester module (e.g., by setting PYTHONPATH or running from parent dir)
    # Example: python -m backtester.strategy
    # For that to work, data.py also needs pandas for its example.
    # I'm using `import pandas as pd` inside __main__ for `data.py` and here for `strategy.py`
    # to make them runnable, but in the actual engine, pandas will be a core dependency.
    try:
        import pandas as pd # For example usage
    except ImportError:
        print("Please install pandas to run this example: pip install pandas")
